name: CI
'on':
  - pull_request
  - push
env:
  LANG: C
jobs:
  codingStyle:
    name: 'JS Coding Style'
    runs-on: ubuntu-20.04
    steps:
      -
        name: 'Check out the source'
        uses: actions/checkout@v3
      -
        name: 'Set up node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: 'Install dependencies'
        run: 'npm clean-install'
      -
        name: 'Run semistandard'
        run: 'npx semistandard ''**/*.js'''
  license:
    name: 'Check Licenses'
    runs-on: ubuntu-20.04
    steps:
      -
        name: 'Check out the source'
        uses: actions/checkout@v3
      -
        name: 'Set up node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: 'Install dependencies'
        run: 'npm clean-install'
      -
        name: 'Run license-checker'
        run: |
          npx license-checker-rseidelsohn \
              --onlyAllow '0BSD;Apache-2.0;BSD-2-Clause;BSD-3-Clause;CC-BY-3.0;CC0-1.0;ISC;MIT' \
              --production \
              --summary
  codingStylePhp:
    name: 'PHP Coding Style (deploy script)'
    runs-on: ubuntu-20.04
    steps:
      -
        name: 'Check out the source'
        uses: actions/checkout@v3
      -
        name: 'Set up PHP 8.1'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      -
        name: 'Run PHPCS (PSR-12)'
        run: './bin/phpcs -s --standard=PSR12 --extensions=php --ignore=node_modules .'
